name: tool_commander
description: Vega tool commander.
version: 1.2.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependency_overrides:
  intl: any
  collection: any

dependencies:
  core_dart:
    #path: ../core_dart
    git:
      url: "git@gitlab.vega.com:vega/core_dart.git"
      ref: "refs/tags/241019.001"

  intl: ^0.18.0
  collection: ^1.17.1

  path: ^1.8.3
  args: ^2.6.0
  postgres: ^2.5.2
  postgres_pool: ^2.1.5
  redis: ^3.1.0
  dio: ^5.1.1
  bcrypt: ^1.1.3

  image: ^4.0.17

  pubspec_yaml: ^3.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

executables:
  vtc: main
