name: api_cron
description: A server app using the shelf package and Docker.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependency_overrides:
  intl: any

dependencies:
  core_dart:
    path: ../core_dart
    #git:
    #  url: "git@gitlab.vega.com:vega/core_dart.git"
    #  ref: "refs/tags/241105.002"

  intl: ^0.19.0
  collection: ^1.19.0
  path: ^1.8.0
  yaml: ^3.1.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  riverpod: ^2.1.1
  postgres: ^3.2.1
  dio: 5.2.1

  mime: ^1.0.5
  compute: ^1.0.2
  mailer: ^6.1.0

  http2: ^2.3.0
  dart_jsonwebtoken: ^2.10.0

dev_dependencies:
  http: ^1.2.1
  lints: ^4.0.0
  test: ^1.25.7

vega:
  localization:
    locales:
      - sk
      - en
      - es
    assets: langs/
