name: core_dart
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  #sdk: ">=2.19.4 <3.0.0"
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.12.0 # flutter_test depends on 1.12.0
  intl: ^0.19.0
  collection: ^1.19.0
  uuid: ^4.5.1
  convert: ^3.1.1
  path: ^1.8.3

  logger: ^2.3.0
  yaml: ^3.1.2

  hive: ^2.2.3
  riverpod: ^2.5.1

  petitparser: ^6.0.2

  image: ^4.2.0
  blurhash_dart: ^1.2.1

  # dio shit, should to be removed
  dio: 5.2.1 # don not use 5.4.3+1 !!!
  http_parser: 4.0.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.7
